#!/bin/sh /etc/rc.common
#
# Copyright (C) 2014-2022 Jian Chang <aa65535@live.com>
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

START=80
STOP=15
USE_PROCD=1
NAME=shadowsocks-ipset

gen_config_file() {
    local section="${1}"
    config_get enabled "${section}" "enabled"
    if [ ! ${enabled} ]; then
        return
    fi
    [ ! -d /tmp/dnsmasq.d ] && mkdir -p /tmp/dnsmasq.d
    config_get ipset_name "${section}" "ipset_name"
    config_file_name="/tmp/dnsmasq.d/ipset_${ipset_name}.conf"
    rm -f "${config_file_name}"
    config_get_bool dns_forward "${section}" "dns_forward"
    if [ ${dns_forward} ]; then
        config_get upstream_dns_server "${section}" "upstream_dns_server"
    fi
    handle_domain() {
        local domain="${1}"
        if [ ${dns_forward} ]; then
            echo "server=/${domain}/${upstream_dns_server}" >>"${config_file_name}"
        fi
        echo "ipset=/${domain}/${ipset_name}" >>"${config_file_name}"
    }
    config_list_foreach "${section}" "managed_domain" handle_domain
}

gfwlist_2_dnsmasq() {
    dns_server=$(uci get shadowsocks-ipset.@ipsets[0].upstream_dns_server | tr '#' ' ' | awk '{print$1}')
    dns_port=$(uci get shadowsocks-ipset.@ipsets[0].upstream_dns_server | tr '#' ' ' | awk '{print$2}')
    ss-gfwlist -d ${dns_server} -p ${dns_port} -s ss_spec_dst_fw -o /tmp/dnsmasq.d/ipset_gfwlist_fw.conf
}

gen_config_files() {
    rm -rf /tmp/dnsmasq.d/ipset_*.conf
    gfwlist_2_dnsmasq
    config_load 'shadowsocks-ipset'
    config_foreach gen_config_file 'ipsets'
}

start_service() {
    gen_config_files
    /etc/init.d/dnsmasq restart
}

stop_service() {
    echo "shadowsocks-ipset stoped"
}

service_triggers() {
    procd_add_reload_trigger $NAME
}
