#!/bin/sh /etc/rc.common

START=85
STOP=85
USE_PROCD=1

BIN="/usr/sbin/daemon"
NETWORK="/usr/sbin/network_watchdog.sh"

start_service() {
	enabled=$(uci get daemon.main.enabled)
	exestart=$(uci get daemon.main.exestart)
	if [ "$enabled" = "1" ]; then
		sh -c "${exestart}"
		procd_open_instance
		procd_set_param respawn ${respawn_threshold:-0} ${respawn_timeout:-1} ${respawn_retry:-1073741824}
		procd_set_param command $BIN
		procd_close_instance
	fi
	watchnet=$(uci get daemon.main.watchnet)
	if [ "$watchnet" = "1" ]; then
		procd_open_instance
		procd_set_param respawn
		procd_set_param command $NETWORK
		procd_close_instance
	fi
}

stop_service() {
	exestop=$(uci get daemon.main.exestop)
	sh -c "${exestop}"
}
