#!/bin/sh
uci -q batch <<-EOF >/dev/null
    delete ucitrack.@shadowsocks-ipset[-1]
    add ucitrack shadowsocks-ipset
    set ucitrack.@shadowsocks-ipset[-1].init=shadowsocks-ipset
    commit ucitrack
EOF
exit 0
